language: php

sudo: false

branches:
  only:
    - master

php:
  - 5.5
  - hhvm

env:
  - DB=mysql

# Disables default git submodules.
# This is done to only download the modules required for testing.
git:
  submodules: false

before_install:
  - git submodule update --init frontend/server/libs/log4php frontend/server/libs/adodb frontend/server/libs/google-api-php-client

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `omegaup-test`'
  - mysql omegaup-test < frontend/private/bd.sql
  - mysql omegaup-test < frontend/private/countries_and_states.sql
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ]; then pyrus install pear/PHP_CodeSniffer && phpenv rehash; fi

script:
  - phpunit --bootstrap frontend/tests/bootstrap.php --configuration frontend/tests/phpunit.xml frontend/tests/controllers
  - python stuff/i18n.py --validate
  - python stuff/update-templates.py --validate
  - bash stuff/whitespace-purge.sh --validate
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ]; then bash stuff/php-format.sh --validate; fi

notifications:
  slack:
    secure: BGGaWyzHJ0Fb+oU93EjuZZ7e/2GK+dT1Ao3W5Ulbv8dQbzV761151T4Vby40hxIMim+MoXq+zL2GQ9i7tg6GnEMNVVBpHqL40S1Y5qZbZMPkcy0vq14t41uX5vJNIYVp24IvTxWKy3XA2+cq7irILTD2lMzv6xMveawhYdiqkwU=
