language: php

php:
  - 5.5
  - hhvm

env:
  - DB=mysql

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `omegaup-test`'
  - mysql omegaup-test < frontend/private/bd.sql
  - mysql omegaup-test < frontend/private/countries_and_states.sql

script:
  - phpunit --bootstrap frontend/tests/bootstrap.php --configuration frontend/tests/phpunit.xml frontend/tests/controllers
  - python stuff/i18n.py --validate
  - python stuff/update-templates.py --validate
